package com.nexvary.securitysuite.wireless

data class NameSignature(
    val label: String,
    val category: DeviceCategory,
    val severity: AlertSeverity,
    val keywords: List<String>,
    val source: RadioSource? = null,
)

object BuiltInSignatures {
    val entries: List<NameSignature> = listOf(
        NameSignature("Apple AirTag / Find My", DeviceCategory.TRACKER, AlertSeverity.MEDIUM, listOf("AIRTAG", "FIND MY")),
        NameSignature("Samsung SmartTag", DeviceCategory.TRACKER, AlertSeverity.MEDIUM, listOf("SMARTTAG", "GALAXY SMARTTAG")),
        NameSignature("Tile tracker", DeviceCategory.TRACKER, AlertSeverity.MEDIUM, listOf("TILE")),
        NameSignature("Chipolo tracker", DeviceCategory.TRACKER, AlertSeverity.MEDIUM, listOf("CHIPOLO")),
        NameSignature("Pebblebee / moto tag", DeviceCategory.TRACKER, AlertSeverity.MEDIUM, listOf("PEBBLEBEE", "MOTO TAG")),
        NameSignature("DJI drone / controller", DeviceCategory.DRONE, AlertSeverity.MEDIUM, listOf("DJI", "MAVIC", "MINI 4", "AVATA")),
        NameSignature("Autel drone", DeviceCategory.DRONE, AlertSeverity.MEDIUM, listOf("AUTEL", "EVO")),
        NameSignature("Skydio drone", DeviceCategory.DRONE, AlertSeverity.MEDIUM, listOf("SKYDIO")),
        NameSignature("Parrot drone", DeviceCategory.DRONE, AlertSeverity.MEDIUM, listOf("PARROT", "ANAFI", "BEBOP")),
        NameSignature("HOVERAir drone", DeviceCategory.DRONE, AlertSeverity.MEDIUM, listOf("HOVERAIR", "HOVER X1")),
        NameSignature("Axon body camera", DeviceCategory.BODY_CAMERA, AlertSeverity.MEDIUM, listOf("AXON", "AXON BODY")),
        NameSignature("WatchGuard body camera", DeviceCategory.BODY_CAMERA, AlertSeverity.MEDIUM, listOf("WATCHGUARD VIDEO", "BODYCAM", "BODY CAM", "BWC")),
        NameSignature("Digital Ally camera", DeviceCategory.BODY_CAMERA, AlertSeverity.MEDIUM, listOf("DIGITAL ALLY")),
        NameSignature("GoPro camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("GOPRO", "HERO")),
        NameSignature("DJI Osmo camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("OSMO")),
        NameSignature("Insta360 camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("INSTA360")),
        NameSignature("Reolink camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("REOLINK")),
        NameSignature("Hikvision camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("HIKVISION", "HIK-")),
        NameSignature("Dahua camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("DAHUA")),
        NameSignature("Ring camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("RING-", "RING DOORBELL", "RING CAMERA")),
        NameSignature("Arlo camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("ARLO", "ARLO_VMB")),
        NameSignature("eufy camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("EUFY", "EUFYCAM")),
        NameSignature("Wyze camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("WYZE", "WYZECAM")),
        NameSignature("Nest camera", DeviceCategory.CAMERA, AlertSeverity.LOW, listOf("NESTCAM", "NEST CAM", "NEST-HELLO")),
        NameSignature("Tesla vehicle", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("TESLA")),
        NameSignature("Mercedes MBUX", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("MBUX", "MERCEDES")),
        NameSignature("BMW vehicle", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("BMW")),
        NameSignature("Audi MMI", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("AUDI MMI", "AUDI_")),
        NameSignature("Uconnect vehicle", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("UCONNECT")),
        NameSignature("Rivian vehicle", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("RIVIAN")),
        NameSignature("CarPlay network", DeviceCategory.VEHICLE, AlertSeverity.INFO, listOf("CARPLAY")),
        NameSignature("Meshtastic node", DeviceCategory.MESH, AlertSeverity.INFO, listOf("MESHTASTIC")),
        NameSignature("MeshCore node", DeviceCategory.MESH, AlertSeverity.INFO, listOf("MESHCORE")),
        NameSignature("goTenna node", DeviceCategory.MESH, AlertSeverity.INFO, listOf("GOTENNA")),
        NameSignature("Helium device", DeviceCategory.MESH, AlertSeverity.INFO, listOf("HELIUM")),
        NameSignature("Flipper Zero", DeviceCategory.OTHER, AlertSeverity.MEDIUM, listOf("FLIPPER ZERO", "FLIPPER")),
        NameSignature("WiFi Pineapple", DeviceCategory.OTHER, AlertSeverity.MEDIUM, listOf("PINEAPPLE", "HAK5")),
        NameSignature("Pwnagotchi", DeviceCategory.OTHER, AlertSeverity.MEDIUM, listOf("PWNAGOTCHI")),
        NameSignature("Marauder / Deauther", DeviceCategory.OTHER, AlertSeverity.MEDIUM, listOf("MARAUDER", "DEAUTHER", "ESP32MARAUDER")),
        NameSignature("Meta smart glasses", DeviceCategory.WEARABLE, AlertSeverity.LOW, listOf("RAY-BAN META", "META VIEW", "RAYBAN")),
        NameSignature("Snap Spectacles", DeviceCategory.WEARABLE, AlertSeverity.LOW, listOf("SPECTACLES")),
        NameSignature("Vuzix glasses", DeviceCategory.WEARABLE, AlertSeverity.LOW, listOf("VUZIX")),
        NameSignature("Oura wearable", DeviceCategory.WEARABLE, AlertSeverity.INFO, listOf("OURA")),
        NameSignature("Garmin wearable", DeviceCategory.WEARABLE, AlertSeverity.INFO, listOf("GARMIN")),
        NameSignature("Fitbit wearable", DeviceCategory.WEARABLE, AlertSeverity.INFO, listOf("FITBIT")),
        NameSignature("Ruuvi sensor", DeviceCategory.SENSOR, AlertSeverity.INFO, listOf("RUUVI")),
        NameSignature("Govee sensor", DeviceCategory.SENSOR, AlertSeverity.INFO, listOf("GOVEE")),
        NameSignature("SensorPush", DeviceCategory.SENSOR, AlertSeverity.INFO, listOf("SENSORPUSH")),
        NameSignature("Radiacode", DeviceCategory.SENSOR, AlertSeverity.INFO, listOf("RADIACODE")),
        NameSignature("UniFi network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("UNIFI", "UBIQUITI"), RadioSource.WIFI),
        NameSignature("MikroTik network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("MIKROTIK"), RadioSource.WIFI),
        NameSignature("Cisco network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("CISCO"), RadioSource.WIFI),
        NameSignature("Aruba network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("ARUBA"), RadioSource.WIFI),
        NameSignature("Ruckus network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("RUCKUS"), RadioSource.WIFI),
        NameSignature("Meraki network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("MERAKI"), RadioSource.WIFI),
        NameSignature("OpenWrt network", DeviceCategory.NETWORK, AlertSeverity.INFO, listOf("OPENWRT"), RadioSource.WIFI),
        NameSignature("Cradlepoint gateway", DeviceCategory.NETWORK, AlertSeverity.LOW, listOf("CRADLEPOINT", "IBR900", "IBR1700", "R1900"), RadioSource.WIFI),
        NameSignature("Sierra AirLink gateway", DeviceCategory.NETWORK, AlertSeverity.LOW, listOf("AIRLINK", "SIERRA"), RadioSource.WIFI),
        NameSignature("Schlage lock", DeviceCategory.ACCESS_CONTROL, AlertSeverity.LOW, listOf("SCHLAGE")),
        NameSignature("August lock", DeviceCategory.ACCESS_CONTROL, AlertSeverity.LOW, listOf("AUGUST")),
        NameSignature("Nuki lock", DeviceCategory.ACCESS_CONTROL, AlertSeverity.LOW, listOf("NUKI")),
        NameSignature("SALTO access", DeviceCategory.ACCESS_CONTROL, AlertSeverity.LOW, listOf("SALTO")),
        NameSignature("Dormakaba access", DeviceCategory.ACCESS_CONTROL, AlertSeverity.LOW, listOf("DORMAKABA")),
    )
}
